### ISSUE TITLE
Document ALL validator methods in Shorthand and Expressions in README.md

### ISSUE THREAD

**Issue by frank-richards** [martinswiderski/valdi#10]
Otherwise the documentation is not going to be clear (does not show new min() max() and string length limits in v0.0.372) @spooky-monkey @martinswiderski any ideas when? This really is a pushing off factor in module adoption.

**Comment by spooky-monkey** [comment]
That should be easy enough as we have full tests coverage and can compile .md easily, @martinswiderski what is priority of this over other things we talked about?

**Comment by martinswiderski** [comment]
@spooky-monkey this is a proper **must have** - thanks! And since you have mentioned reformatting tests I can perhaps do that tomorrow some time.

**Comment by martinswiderski** [comment]
Done and ready in branch for release 0.0.373

https://github.com/martinswiderski/valdi/blob/v0.0.373/README.md#examples
