### ISSUE TITLE
NiceHave: Valdi.expression.factory() should produce .result() that can be re-used

### ISSUE THREAD

**Issue by frank-richards** [martinswiderski/valdi#8]
Problem:
 * Currently Expression does not receive value and therefore cannot be revalidated on new entry
* This is probably very useful for stuff like scoring or time ranges, but does not make sense for simple valiidation

Suggestion:
 * Allow only use of Shorthand definitions (for AND conditions)
* Allow present behaviour with added .value() that would re-run validation of **alll** criteria

**It is a nice have but perhaps worth doing**

**Comment by spooky-monkey** [comment]
The challenge will be to preserve behaviour as per current unit tests... I can pick this one up over the weekend.

**Comment by martinswiderski** [comment]
In old repo in BB I still have a version that does exactly that. However, it may not fly with current tests and the api interface designed.

**Comment by martinswiderski** [comment]
Hi, we will use obj.and() and obj.or() with patterns described here:
https://github.com/martinswiderski/valdi/blob/v0.0.374/README.md#cookbook-26

In version 0.0.4 with some fixes and improvements comes adding **nested** simple.* instances
