### ISSUE TITLE
npm badge still shows v0.0.371 for master being at v0.0.372 (and npm published)

### ISSUE THREAD

**Issue by frank-richards** [martinswiderski/valdi#9]
It may just be caching...

**Comment by spooky-monkey** [comment]
![versions-mismatch](https://cloud.githubusercontent.com/assets/26343791/24276453/c2ceebd8-102e-11e7-9f0d-53c3c8488051.png)

**Comment by martinswiderski** [comment]
Guys, let it be. I think it is some funny caching... @moonlit-sky removed it once and I added it back so the npm version of README.md is much longer online now. We'll see in a day or two.

**Comment by martinswiderski** [comment]
It is non-issue, a caching problem. Now shows correct version both ends. Closing it.
